import type { Metadata } from 'next'
import { DM_Sans } from 'next/font/google'
import './globals.css'

const dm_sans = DM_Sans({ subsets: ['latin'],
                          display: 'swap',
                          weight: ["300", "400", "500"],
                          style: ["italic", "normal"],
                          variable: "--font-dmsans" })

export const metadata: Metadata = {
  title: 'Form',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={dm_sans.className}>{children}</body>
    </html>
  )
}
